version: '3'

services:
  ast:
    container_name: ast
    image: ast
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    volumes:
    #  - /home/arashi/work/ast:/app/ast
      - ./audio_samples:/app/ast/audio_samples
      - ./pretrained_models:/app/ast/pretrained_models
      - ./label_csvs:/app/ast/label_csvs
      - ./logs:/app/ast/logs
      
    ports:
      - 7777:7777
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
