version: '3'

services:
  ast:
    container_name: ast
    image: ast
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    runtime: nvidia
    shm_size: 8gb
    volumes:
    #  - /home/arashi/work/ast:/app/ast
      -  /home/arashi/work/ast_files:/ast_files
    ports:
      - 7777:7860
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
